### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by robmarkcole**
Key changes:
- Improve clarity of Readme
- Adds quickstart notebook (url to be updated once merged to main)
- Moves most auth methods to dedicated AUTHENTICATION documentation

### CODE REVIEW

**Comment by robmarkcole** [comment]
Do we need to support conda at all? Just sounds like more work

**Comment by nkarasiak** [comment]
About the credentials, I think an nice and clean solution would be, as for AWS, to have a `Copy Credentials` part to avoid issues when copy/paste each line and to find the correlation between key and value. Easier for everyone, and I think easy to implement in the UI side.

**Comment by nkarasiak** [comment]
> Do we need to support conda at all? Just sounds like more work

Sure it's a bit more work, maybe not in the first place but conda is something very important in the geospatial community as we have some high binaries dependencies (gdal 👀) . And mixing pip/conda is not something recommended.

**Comment by robmarkcole** [comment]
@nkarasiak we will enable downloading the credentials from the platform.

For conda, could you create an issue covering: deploy the package to conda - I can pick it up.

Thanks!

**Comment by nkarasiak** [comment]
I just see that some files have been moved from root to docs (CHANGELOG.md for example). 

I just control the whole repo and merge.

**Pull request merged**
